### ISSUE TITLE
fix(persistence): implement the Git-core Fleet → Project → Task → Plan → Attempt architecture after relock

### ISSUE THREAD

**Issue by atqamz** [atqamz/hand#339]
# Canonical v19 implementation umbrella

Implementation tracker, not semantic architecture authority. Technical completion is recorded in this body; issue state/labels/milestone/lock are not completion evidence and are not changed by this mandate. Historical comments remain provenance, not current sequencing authority.

## Authority and scope

Current semantic authority is `docs/architecture/v19-contracts/manifest-v2.md` at `899e7a9aa2e383d3b3f91689fe5a897c5bab59ec`, contract-set SHA-256 `03314c8f9dad1e0716062b1b06afa627b177295643581b1fbae3571d93d7e21c`. It indexes #323/#324/#343/#345/#346/#347 and #348 revision 2. Revision-1 `manifest.md` and superseded `348-cutover-archive.md` remain immutable history.

Exact relational authority is #344's immutable DDL/proof at `67ca4b35b773ef25ac9ff88cd1b16213153ed498`. #304's current body owns Decision/Answer semantics. This tracker neither changes those artifacts nor silently relocks them.

#338 LaunchSpec, #340 monitoring/stale-wake safety, #353/#355 Supervisor integration, #331 and #357–#360 Fleet/registry isolation, and #524–#528 cutover decisions/probes are historical prerequisites whose current consumers must still be verified. #305 owns exact-candidate qualification, not architecture. Future board/Source/ActionIntent/automation/v1 work (#306–#322, #325–#329) is not added to 0.8.0 merely through semantic cross-references.

## Current evidence and progress boundary

Static baseline: `main` at `47bc0e1e950dd59d3f816306e625e45da5b5dd4f`, 2026-09-11 UTC. This is not local or release qualification.

- Design artifacts are landed. #517 (`818efd3f57087bf9b85ad433dfdbb0c613d4ead3`) established exact read-only schema-family classification. Its historical full-CI claim is preserved in the existing comment, not promoted into evidence for subsequent code.
- Substantial implementation slices have landed since the previous queue: #529–#550 cutover helpers, #551 archive-manifest-before-freeze ordering, #552/#553/#555/#556 core writers, #557–#559 Backoff/Hold/Repair, #561–#570 and #572 resource/executor operations, and #573–#578/#580 WorkerInput/Acknowledgement/Wake/drain/CLI/Herdr work. These are work to retain and reconcile, not a claim that every acceptance criterion or production entry point is complete.
- `internal/store/store.go` still contains the legacy Task→Attempt schema and `Open` still calls legacy `migrateSchema`/`migrateLegacy`. A helper, exported canonical method, or CLI scaffold does not establish a fully switched production flow.
- #348 has a release-blocking static source-lock counterexample: raw source hashing/copying opens and closes the locked database inode while SQLite exclusion must remain continuous. Its same-process SQLite tests do not prove exclusion of an independent v0.7.2 process. See the current #348 body for exact functions, minimal repair direction and required process/platform proof.
- Open draft #581 at `150a2dac5baa43cd69d5be19b371330baba85b20` is a WorkerReport schema probe, not completed ingestion. Continue valid work on that branch; remove deliberate-failure/probe artifacts before integration.
- Open draft #571 at `484ba27ad4c7a747a2a3dae889c1c272b48fdc88` is based on `8b69de3ee4249810fe6d895edd1faae99aec6d96` and overlaps landed #570. Its temporary self-pushing workflow is not product scope. Compare the final delta to current `internal/herdr/exact_launch.go` and `internal/store/v19launch_herdr.go`; preserve valid fixes and avoid a duplicate Launch implementation.

No numerical technical-completion percentage is established by counting merged slices. The full requirement→contract→implementation→production caller→test→exact revision→verification matrix remains necessary before completion.

## Engineering decisions

1. Retain #348 revision 2, including original-byte archival followed by its exact certified frozen-bridge transaction. “No source mutation” is not the acceptance rule: no unapproved source normalization/migration is allowed, but the certified freeze is required. Repair lock/descriptor lifetime before enabling cutover. Expected DDL impact NONE; neither hashes nor a Linux-only optional locking mode replace portable proof.
2. #519 runtime generations/bundles/integration are user-global mechanism ownership, not Fleet v19 ontology. #502's executable-replacement failure must be solved consistently with immutable published generations and positive global non-use before cleanup. Never trade cross-Fleet safety for successful upgrade/cleanup.
3. Retain #497 Option A: no first-class soft-turn-cancel. Escape-like cancellation is not WorkerWake, positive executor cessation, or semantic completion. Any future expansion needs its own explicit contract change.
4. #524 resolved the earlier architecture contradiction, not the current implementation's safety. A closed issue/probe/green predecessor does not discharge #348.
5. #301 has already decided the storage direction: a minimal append-only operator archive fact distinct from Task lifecycle. The current #344 artifact has no such classification. A versioned #344 DDL/proof relock and corresponding #345/#347 semantic revisions are required before archive implementation. Preserve the current immutable artifacts as historical authority; a transient filter or lifecycle-derived approximation does not meet the requirement.
6. #346 now records exact-executable and process-incarnation gaps in the landed Herdr Launch identity, propagated to Interrupt/WorkerWake, plus cessation-inventory and Worker acknowledgement actor-boundary qualification gaps. Repair and prove these before production wiring. An unsupported mandatory operation is a release blocker, not permission to reduce the required baseline.

## Remaining execution order

This umbrella is not a sequencing prerequisite on itself. Semantic references do not create cycles.

0. **Publication safety before any implementation merge:** current CI publishes edge artifacts on ordinary main pushes. At exact baseline, CI run `34498768941` completed its Edge Publish job, including the publish step. Under the no-publication mandate, first establish and verify a non-publishing implementation-merge path under #305; that prerequisite change must itself be safe to merge without publication. Preserve all test/review/protection gates. Do not treat npm environment approval or leaving #516 open as protection against edge publication. If no authorized code-only path can prevent the side effect, keep implementation PRs unmerged and name the minimum operator action.
1. **Safety gates, independently parallel:** repair and prove #348 source exclusion/freeze/recovery; implement/verify #519 with #502/#518 runtime ownership and lifetime fixes. Keep current ordinary runtime behavior until its replacement is coherent. Diagnose #503/#504/#523/#535 test ownership/observation failures without weakening assertions.
2. **Complete canonical service families from landed work:** reconcile Task/Plan/Attempt retry/replan/advance/terminalization, Hold/Backoff/Repair, WorktreeCreate/Remove, SessionAcquire/Release, Launch/Executor/Interrupt, WorkerInput/Ack/Wake, and recovery dispatch. Inspect every normative remaining family, including report acknowledgements, Decision/Answer, TerminalReceipt/Qualification/Plan acceptance/Integration and Production/Artifact/Publication where this baseline requires them; do not infer implementation from DDL presence. #323/#324 routing/config must feed real future Attempt/Launch creation with immutable provenance and secret-safe boundaries. Coordinate shared store/schema edits.
3. **Continue #581 report ingestion**, with exact Attempt/source-prefix identity, deterministic replay, rewrite/truncation handling, exact acknowledgement and bounded verified incremental work. Continue only unique valid #571 work after overlap/probe/workflow cleanup; require final-head independent review.
4. **Parallel after the required writers exist:** #304 durable Decision/Answer writers do not depend on UI/read-model completion. #302 derives canonical Attention; #303 consumes that derivation for FleetSnapshot/status/orient. #304 presentation consumes #303 but must not be used to cycle the durable writer behind its own consumer. #301 follows its mandatory contract/DDL relock and required lifecycle/obligation writers; its read-model presentation then composes with #302/#303.
5. **Coherent production integration:** fresh init/create, ordinary mutations, routing/config, native Git worktrees, actual Worker launch/drain/wake/report paths, Decision/input, reconciliation, qualification/integration, and status/orient/watch must agree. Read-only entry points remain mutation-free. Retire fresh-v19 legacy Send/Treehouse/flattened authority only after every caller is accounted for; retain explicit legacy cutover support where required.
6. **Exact-candidate #305 qualification:** test source+DDL+runtime+dependencies+platforms+artifacts together, including #348/#519 and required historical registry/launch/Supervisor regressions. #354 remains the historical v0.7 Git+Treehouse+Herdr qualification owner; it is not authority to require Treehouse in fresh v19 or claim Git+Herdr readiness without production dependency proof. #500 CI reliability, #505 gate completion semantics, #520 registration transport and #579 operator safety remain milestone work with their own scoped acceptance. #300/#484 documentation can proceed independently against current source.

Do not merge release PR #516 or publish/tag/package without separate permission. Treat #582 at `ea4542ac9428e8ca9b6190f17cb20a3376520551` as a dependency change requiring exact-revision qualification, not the portable fix for #348. Its actual diff includes go.mod/go.sum and the flake.nix vendorHash update; verify that final dependency set and all cutover proofs rather than assuming the hash is missing or an optional Linux locking mode fixes portability.

## Acceptance / definition of technical completion

- Exact current contracts and #344 schema/proof agree with production code. Any discovered contract defect is explicitly versioned/re-proved/relocked first; preserve old evidence.
- Supported v0.7.2 cutover meets #348 continuous cross-process exclusion, original immutable archive, certified freeze, truthful import, crash convergence and native-platform proof. No fabricated execution/input/effect history.
- Fresh production execution follows Fleet→Project→Task→Plan→Attempt and native WorktreeBinding→SessionBinding→Launch/ExecutorBinding. No legacy table assumptions or parallel authority survive in fresh-v19 callers.
- WorkerInput durable ≠ WorkerWake ≠ exact acknowledgement ≠ action/outcome. Claim/observation/authority/semantic completion remain separate. Submitted is committed before external mutation; uncertain effects are observed before repeat. Historical actions never retarget successors.
- Routing/config, all required canonical writers/recovery dispatch, bounded indexed read models, archive semantics, and operator surfaces are wired and verified through actual execution paths. Unknown remains unknown; destructive cleanup requires positive exact ownership and preservation proof.
- #519 cross-Fleet runtime safety and #497 no-soft-turn-cancel behavior are verified. All remaining 0.8.0 items retain their acceptance; do not reduce scope or change metadata to report success.
- Final diff receives independent Codex review; required checks/approvals and actionable findings pass at the exact head/base; default-branch integration is verified after merge. Bodies record exact evidence, not worker claims or nearby green CI.
- Release readiness is separate from publication. Record unperformed publication-dependent acceptance as pending authorization/evidence, not complete. Do not close/reopen issues or use automatic closing keywords under the body-only mandate.

**Comment by atqamz** [comment]
Implementation audit update: #348 source-safety slice is blocked on #524 before publication/writer-exclusion code can be considered correct. Current v0.7.2 `MigrationLock` is not held by ordinary DB writers, and SQLite `mode=ro` cannot acquire the IMMEDIATE/EXCLUSIVE writer reservation needed to close future-writer races. Do not implement the publication boundary by treating a SHARED read transaction as writer exclusion. #517 remains independently landable because it is read-only classification only. DDL impact: NONE.

**Comment by atqamz** [comment]
Implementation slice landed: #517 merged to `main` as `818efd3f57087bf9b85ad433dfdbb0c613d4ead3` after exact-head full CI (Contract/Lint/Nix, Linux/ARM/Windows/macOS, and all E2E bootstrap jobs) completed successfully. This establishes read-only typed schema-family identity only: exact canonical v19, exact supported v0.7.2 legacy source, missing/empty/unknown fail-closed boundaries. It does not perform cutover or source mutation. Next #348 source-safety/publication work remains blocked on #524 until writer exclusion and crash-recoverable freeze semantics are mechanically proved and, if necessary, #348 is deliberately amended/relocked. DDL impact: NONE.

**Comment by atqamz** [comment]
## 2026-09-21 manual-review integration evidence

This is an exact-revision progress record, not a contract relock, new sequencing authority, or technical-completion declaration. The tracker body still describes a 2026-09-11 baseline; in particular #581 is no longer an open schema probe.

Under explicit operator authorization to perform manual review and squash merge acceptable PRs, the following are now on main:

- #597: `650a7c616ac6da55a1d7a6653d4ef8cc34333140`, inherited launch-instruction currentness, including cross-harness and CRLF boundaries. Reviewed head `47298e7b`; CI `35577384896` successful.
- #581: `700367514ff4e15fd7399de6aaff7e2fbcb06ff3`, canonical WorkerReport ingestion and exact acknowledgement, including relational-tail fork rejection. Reviewed head `16d3ea25`; CI `35561351001` successful. Production source-witness construction/report wiring remains separate.
- #592: `86ffe7406ad7a3dcff5e62f6c52e122fe1d53c32`, pinned source descriptors and ordered SQLite teardown with independent-process exclusion regressions. Reviewed head `33b4db7f`; CI `35055704572` successful. This does not declare all #348 integration/qualification complete.
- #596: `387481155618a62cdfb938dfdb41104fc09811e5`, one-line Nix installer CI dependency update. Reviewed head `72088b1a`; CI `35606095416` successful.
- #595: `10f81b76789308d49bc9ab206756df0492ba2d76`, SQLite 1.59.0 with matching libc 1.75.7, checksums and verified Nix vendorHash. Reviewed head `fd9a1439`; CI `35606227523` successful. No optional locking mode or canonical DDL change.

Still under current-candidate CI, not yet merged at this observation: #587 head `23ccf3c8` (CI `35607012233`) and #590 head `72b609fa` (CI `35610965375`). Manual review repaired real Git whitespace-rewrite loss, an unsafe live-session restart after a Hand-generation change, a cross-PR deterministic-generation fixture mismatch, and a stale-waiter wake-claim handover race. Actual full-repository Go 1.26.5 affected-package race suites and full Linux E2E passed on their integrated candidates; the ordinary native-platform CI remains authoritative for those remaining gates.

Publication boundary checked against current source: `.github/workflows/ci.yaml` at `10f81b76` is contents-read-only validation and does not invoke Edge. `edge.yaml` is reusable via workflow_call; release build/npm publication in `release.yaml` is gated on release_created. The old baseline statement about an Edge Publish job in ordinary CI must not be assumed to describe current CI. #516 remains unmerged and no release/tag command was issued. No test/protection rules were disabled.

All five temporary review-only workflows were removed from the scratch branch after publishing their tested code onto the original PR branches; none entered main or a feature PR. Frozen v19 contracts were not edited. These merges are not evidence that legacy Open/production dispatch has switched to canonical v19, and do not discharge #579/#305 or the full umbrella acceptance matrix.

**Comment by atqamz** [comment]
## Manual-review queue completed — 2026-09-21

All seven non-release PRs from this review queue are now squash-merged. Current main: `c15cbd3d444ef47e8f9cd4321314c6310a59e2b8`.

| PR | Squash commit | Completed CI used for qualification |
| --- | --- | --- |
| #597 | `650a7c616ac6da55a1d7a6653d4ef8cc34333140` | `35577384896` |
| #581 | `700367514ff4e15fd7399de6aaff7e2fbcb06ff3` | `35561351001` |
| #592 | `86ffe7406ad7a3dcff5e62f6c52e122fe1d53c32` | `35055704572` |
| #596 | `387481155618a62cdfb938dfdb41104fc09811e5` | `35606095416` |
| #595 | `10f81b76789308d49bc9ab206756df0492ba2d76` | `35606227523` |
| #587 | `e37693bdd5633033602385fd9ebda3c7253d83e6` | `35607012233` |
| #590 | `c15cbd3d444ef47e8f9cd4321314c6310a59e2b8` | `35610965375`, exact-tree equivalence below |

For #590 the reviewed semantic head `72b609fa`, tested PR merge revision `b6e612bd`, final ancestry-integration head `c8de358e`, and actual main squash commit `c15cbd3d` all have complete tree `914e04dc5a4ab7960495273c897ef1fbd6fd0315`. The final integration resolved the single fixture conflict created by independently squash-merging #587, without changing any byte of the tested tree. CI `35610965375` completed all 17 non-optional jobs successfully; the expensive optional mutation job was skipped. This is exact source-tree qualification, not a claim that a newly triggered integration-head or post-merge run had already completed. Final manual review `5268132590` records the proof.

The manual review also repaired the Git whitespace-rewrite defect, unsafe restart of a live previous Hand generation, stale-waiter wake-claim handover race, and cross-PR deterministic-generation fixture interaction. Their real-repository red/green evidence is recorded in #587/#590. No bot approval or protection/check bypass was fabricated.

The local environment now has a byte-identical full checkout and checksum-verified Go 1.26.5/modules. Four new regression functions passed 20 race repetitions. A redundant local full affected-package run hit one existing mode-0500 permission test because it ran as root; that test passed 20 race repetitions under UID 1000 without changing code. The incomplete root-run matrix is explicitly not reported as fully passing. Full hosted source qualification above passed independently.

Open-PR search now returns only release PR #516. It remains unmerged; no release/tag/publication command was issued. Temporary review workflows were removed and never entered main. This closes the PR-review queue, not the umbrella's canonical production wiring or release qualification requirements. #579 report-source integration, remaining canonical service/read-model families and #305 exact-release qualification are not discharged by counting these merges.

**Comment by atqamz** [comment]
Partial Task lifecycle slice: PR https://github.com/atqamz/hand/pull/648 adds exact pre-Plan Task supersession with one successor and obligation refusals. It does not implement Attempt/Plan acceptance, Task satisfaction, TerminalReceipt, or provider qualification; this issue remains open.

**Comment by atqamz** [comment]
Partial #339/#345 Task supersession landed in PR #648 as 4cd231438346c377ec148713b7e52fbb78d4951d. hand task supersede atomically terminalizes one exact active unplanned Task and creates its linked successor, refusing stale or retired lineage, direct obligations, and unresolved inbound blocked-on-Task Holds. Independent review found no P1/P2; focused store race, CLI E2E, local lint, hosted Lint and Contract passed. This does not establish completion, acceptance, or provider execution. #339 remains open.
